import os
from flask import (
    Blueprint, current_app, flash, g, redirect, render_template, request, url_for
)
from werkzeug.exceptions import abort
from werkzeug.utils import secure_filename
from flaskr.auth import login_required
from flaskr.db import get_db

bp = Blueprint('blog', __name__)

ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif', 'webp'}
VALID_STATUSES = {'new', 'pending', 'complete'}

def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

def save_uploaded_image(file):
    if file and file.filename != '' and allowed_file(file.filename):
        filename = secure_filename(file.filename)
        upload_folder = os.path.join(current_app.static_folder, 'media')
        os.makedirs(upload_folder, exist_ok=True)
        
        filepath = os.path.join(upload_folder, filename)
        file.save(filepath)
        return f"/static/media/{filename}"
    return None

def decode_post_bytes(post):
    """Converts sqlite3.Row object to a dict and decodes BLOB bytes to str."""
    if post is None:
        return None
    post_dict = dict(post)
    if isinstance(post_dict.get('body'), bytes):
        post_dict['body'] = post_dict['body'].decode('utf-8', errors='ignore')
    return post_dict

def create_post(title, body, author_id, image=None):
    """
    Creates a post. 'image' can be:
      - A filename string (e.g. generated by Matplotlib)
      - A FileStorage object from request.files['image']
    """
    filename = None

    if image:
        if isinstance(image, str):
            # Already saved to static media folder (e.g. by astronomy script)
            filename = image
        elif hasattr(image, 'filename') and image.filename != '':
            # Handled from HTML form upload (FileStorage object)
            filename = secure_filename(image.filename)
            upload_folder = os.path.join(current_app.root_path, 'static', 'media')
            os.makedirs(upload_folder, exist_ok=True)
            image.save(os.path.join(upload_folder, filename))

    db = get_db()
    db.execute(
        "INSERT INTO post (title, body, author_id, image) VALUES (?, ?, ?, ?)",
        (title, body, author_id, filename)
    )
    db.commit()

@bp.route('/')
def index():
    db = get_db()
    raw_posts = db.execute(
        'SELECT p.id, title, body, status, created, author_id, username'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' ORDER BY created DESC'
    ).fetchall()
    
    # Decode BLOB byte data for each post
    posts = [decode_post_bytes(p) for p in raw_posts]
    return render_template('blog/index.html', posts=posts)

@bp.route('/create', methods=('GET', 'POST'))
@login_required
def create():
    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        status = request.form.get('status', 'new').lower()
        image_file = request.files.get('image')
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            create_post(title, body, g.user['id'], status=status, image_file=image_file)
            return redirect(url_for('blog.index'))

    return render_template('blog/create.html')

def get_post(id, check_author=True):
    raw_post = get_db().execute(
        'SELECT p.id, title, body, status, created, author_id, username'
        ' FROM post p JOIN user u ON p.author_id = u.id'
        ' WHERE p.id = ?',
        (id,)
    ).fetchone()

    if raw_post is None:
        abort(404, f"Post id {id} doesn't exist.")

    post = decode_post_bytes(raw_post)

    if check_author and post['author_id'] != g.user['id']:
        abort(403)

    return post

@bp.route('/<int:id>/update', methods=('GET', 'POST'))
@login_required
def update(id):
    post = get_post(id)

    if request.method == 'POST':
        title = request.form['title']
        body = request.form['body']
        status = request.form.get('status', post['status']).lower()
        image_file = request.files.get('image')
        error = None

        if not title:
            error = 'Title is required.'

        if error is not None:
            flash(error)
        else:
            if image_file:
                image_url = save_uploaded_image(image_file)
                if image_url:
                    img_tag = f'<p><img src="{image_url}" alt="Uploaded Image" style="max-width:150px; width:100%; height:auto; display:block; margin:0 auto;"></p>'
                    body = f"{img_tag}\n{body}" if body else img_tag

            db = get_db()
            db.execute(
                'UPDATE post SET title = ?, body = ?, status = ?'
                ' WHERE id = ?',
                (title, body, status, id)
            )
            db.commit()
            return redirect(url_for('blog.index'))

    return render_template('blog/update.html', post=post)

@bp.route('/<int:id>/delete', methods=('POST',))
@login_required
def delete(id):
    get_post(id)
    db = get_db()
    db.execute('DELETE FROM post WHERE id = ?', (id,))
    db.commit()
    return redirect(url_for('blog.index'))

@bp.route('/<int:id>/status/<string:new_status>', methods=('POST', 'GET'))
@login_required
def change_status(id, new_status):
    """Quickly update a blog post's status."""
    new_status = new_status.lower()
    
    # Map 'completed' to 'complete' if used interchangeably
    if new_status == 'completed':
        new_status = 'complete'

    if new_status not in VALID_STATUSES:
        flash(f'Invalid status update request.')
        return redirect(url_for('blog.index'))

    # Verify post exists and user owns it
    post = get_post(id)

    db = get_db()
    db.execute(
        'UPDATE post SET status = ? WHERE id = ?',
        (new_status, id)
    )
    db.commit()

    flash(f"Status updated to '{new_status}'.")
    return redirect(url_for('blog.index'))