CRAIGSLIST_CATEGORY_GROUPS = {
    "Community": (
        ("ccc", "Community"),
        ("act", "Activities"),
        ("ats", "Artists"),
        ("kid", "Childcare"),
        ("cls", "Classes"),
        ("eve", "Events"),
        ("com", "General"),
        ("grp", "Groups"),
        ("vnn", "Local News"),
        ("laf", "Lost + Found"),
        ("mis", "Missed Connections"),
        ("muc", "Musicians"),
        ("pet", "Pets"),
        ("pol", "Politics"),
        ("rnr", "Rants & Raves"),
        ("rid", "Rideshare"),
        ("vol", "Volunteers"),
    ),
    "Services": (
        ("bbb", "Services"),
        ("aos", "Automotive"),
        ("bts", "Beauty"),
        ("cms", "Cell / Mobile"),
        ("cps", "Computer"),
        ("crs", "Creative"),
        ("cys", "Cycle"),
        ("evs", "Event"),
        ("fgs", "Farm + Garden"),
        ("fns", "Financial"),
        ("hws", "Health / Wellness"),
        ("hss", "Household"),
        ("lbs", "Labor / Move"),
        ("lgs", "Legal"),
        ("lss", "Lessons"),
        ("mas", "Marine"),
        ("pas", "Pet"),
        ("rts", "Real Estate"),
        ("sks", "Skilled Trade"),
        ("biz", "Small Business Ads"),
        ("trv", "Travel / Vacation"),
        ("wet", "Writing / Education / Translation"),
    ),
    "Housing": (
        ("hhh", "Housing"),
        ("apa", "Apartments / Housing"),
        ("swp", "Housing Swap"),
        ("hsw", "Housing Wanted"),
        ("off", "Office / Commercial"),
        ("prk", "Parking / Storage"),
        ("rea", "Real Estate for Sale"),
        ("roo", "Rooms / Shared"),
        ("sha", "Rooms Wanted"),
        ("sub", "Sublets / Temporary"),
        ("vac", "Vacation Rentals"),
    ),
    "For Sale": (
        ("sss", "For Sale"),
        ("ata", "Antiques"),
        ("ppa", "Appliances"),
        ("ara", "Arts + Crafts"),
        ("sna", "ATV / UTV / Snowmobiles"),
        ("pta", "Auto Parts"),
        ("ava", "Aviation"),
        ("baa", "Baby + Kid"),
        ("bar", "Barter"),
        ("haa", "Beauty + Health"),
        ("bip", "Bike Parts"),
        ("bia", "Bikes"),
        ("bpa", "Boat Parts"),
        ("boo", "Boats"),
        ("bka", "Books"),
        ("bfa", "Business"),
        ("cta", "Cars + Trucks"),
        ("ema", "CDs / DVDs / VHS"),
        ("moa", "Cell Phones"),
        ("cla", "Clothes + Accessories"),
        ("cba", "Collectibles"),
        ("syp", "Computer Parts"),
        ("sya", "Computers"),
        ("ela", "Electronics"),
        ("gra", "Farm + Garden"),
        ("zip", "Free"),
        ("fua", "Furniture"),
        ("gms", "Garage Sale"),
        ("foa", "General"),
        ("hva", "Heavy Equipment"),
        ("hsa", "Household"),
        ("jwa", "Jewelry"),
        ("maa", "Materials"),
        ("mpa", "Motorcycle Parts"),
        ("mca", "Motorcycles"),
        ("msa", "Musical Instruments"),
        ("pha", "Photo + Video"),
        ("rva", "RVs + Camp"),
        ("sga", "Sporting Goods"),
        ("tia", "Tickets"),
        ("tla", "Tools"),
        ("taa", "Toys + Games"),
        ("tra", "Trailers"),
        ("vga", "Video Gaming"),
        ("waa", "Wanted"),
        ("wta", "Wheels + Tires"),
    ),
    "Jobs": (
        ("jjj", "Jobs"),
        ("acc", "Accounting + Finance"),
        ("ofc", "Admin / Office"),
        ("egr", "Architecture / Engineering"),
        ("med", "Art / Media / Design"),
        ("sci", "Biotech / Science"),
        ("bus", "Business / Management"),
        ("csr", "Customer Service"),
        ("edu", "Education"),
        ("etc", "Etc. / Misc."),
        ("fbh", "Food / Beverage / Hospitality"),
        ("lab", "General Labor"),
        ("gov", "Government"),
        ("hum", "Human Resources"),
        ("lgl", "Legal / Paralegal"),
        ("mnu", "Manufacturing"),
        ("mar", "Marketing / PR / Advertising"),
        ("hea", "Medical / Health"),
        ("npo", "Nonprofit"),
        ("rej", "Real Estate"),
        ("ret", "Retail / Wholesale"),
        ("sls", "Sales / Business Development"),
        ("spa", "Salon / Spa / Fitness"),
        ("sec", "Security"),
        ("trd", "Skilled Trade / Craft"),
        ("sof", "Software / QA / DBA"),
        ("sad", "Systems / Network"),
        ("tch", "Technical Support"),
        ("trp", "Transport"),
        ("tfr", "TV / Film / Video"),
        ("web", "Web / Information Design"),
        ("wri", "Writing / Editing"),
    ),
    "Gigs": (
        ("ggg", "Gigs"),
        ("cpg", "Computer"),
        ("crg", "Creative"),
        ("cwg", "Crew"),
        ("dmg", "Domestic"),
        ("evg", "Event"),
        ("lbg", "Labor"),
        ("tlg", "Talent"),
        ("wrg", "Writing"),
    ),
    "Other": (
        ("eee", "Event Calendar"),
        ("rrr", "Resumes"),
    ),
}

CRAIGSLIST_CATEGORIES = {
    code: label
    for category_options in CRAIGSLIST_CATEGORY_GROUPS.values()
    for code, label in category_options
}
